server:
  port: 7002
spring:
  application:
    name: cloud-eureka-server7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #设置与 Eureka server 交互的地址查询服务和注册服务都需要依赖这个地址。
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000