server:
  # 8004表示注册到 zookeeper 服务器的支付服务提供者端口号
  port: 8004
spring:
  application:
    # 服务别名---注册 zookeeper 到注册中心的名称
    name: cloud-provider-payment
  cloud:
    zookeeper:
      # zookeeper服务器（端口默认2181）： localhost:2181
      connect-string: localhost:2181